### ISSUE TITLE
Misspelling of lodash/isUndefined

### ISSUE THREAD

**Issue by selstam** [morzzz007/node-tradfri#1]
Hi!

Had to change the ...
`const isUndefined = require('lodash/isundefined');`
... lines to "lodash/is**U**ndefined" to make this work for me.

Also the coap client can be downloaded from https://libcoap.net/files/ if you don't want to build them yourself.

Anyway, great work! Thank you! :)

**Comment by morzzz007** [comment]
Nice catch, thank you for your pull request :) I plan to add more functionality and unit tests this week. I'll check out the downloadable client if it has tinydtls built in and I'll add it to the documentation.
