### ISSUE TITLE
Set state on group

### ISSUE THREAD

**Issue by nidayand** [morzzz007/node-tradfri#3]
Ok, not really an issue but an enhancement request. It would be great if another method is added to set state (and possibly brightness) on groups as well. As it was missing I assumed that the same setDevice statement can be used for group ids but it doesn't work.

Love the pkg though!

**Comment by morzzz007** [comment]
Thank you! I wrote this package with group support in mind, I just couldn't find the time to finish it. Actually it was pretty easy to implement, check out the updated docs in version 0.1.2, hope it works!

**Comment by nidayand** [comment]
Fantastic - I'll give it a test tonight to confirm the update. Many thanks!

**Comment by nidayand** [comment]
Works like a charm. Thanks for the great work!
